language:
  go

go:
  - "1.12.7"

env:
  - GO111MODULE=on GOPROXY=https://goproxy.io

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)