version: '3'

services:
  shorturl:
    build: ./
    restart: always
    ports:
      - 8090:8080
  redis:
    image: redis:5.0.3-alpine
    restart: always
    volumes:
      - /data/shorturl_redis:/data